dxw/nhs-ei.website

- importer/management/commands/make_footer_links.py
- importer/management/commands/make_home_page.py
- importer/management/commands/runimport.py
- importer/websites.py
There were hardcoded references to `https://staging.nhsei.rkh.co.uk` and `https://nhsei-scrapy.rkh.co.uk/` in the importer code. These now point to `http://localhost:8000` and `:8001` respectively, and are referred to once in `importer/websites.py`.
These changes are completely untested but the previous setup had no chance of working since the RKH websites have been taken down; 
Continue to attempt to import the data from the live NHS E&I website to Wagtail.
> Remove RKH websites from code

- cms/home/tests.py
- script/test
There is a script `fixtures/copy_media.sh` which copies the hero image
and other media into the correct folder for testing -- run that
as a part of the test suite setup
There are still a lot of error-noise (but not failed tests) probably caused by Elastic Search not being found; find a way to suppress or resolve these errors.
> Fix test fixture

- .dockerignore
- .gitignore
.gitignore: ignore backup_ files which are copies of the downloaded website
.dockerignore: the chief one here is requests_cache which is a gigabyte,
which doesn't need to be a part of the Docker context. Added a few other ones --
hiding .git appears to be good practice, the media, and the backup files.
This doesn't impact when the actual website runs.
> Ignoring some files

- .codeclimate.yaml
These are a really noisy check, and Black prevents us from committing anything ridiculously long anyway.
> Disable line length checks in Codeclimate

- .pre-commit-config.yaml
The old `check-byte-order-marker` task has been replaced with `fix-byte-order-marker`.
> Replace deprecated pre-commit task

- cms/categories/wagtail_hooks.py
The admin panel attempts to use the source field, which no longer exists.
Deleted.
> Fix bug: can't load page to make PublicationTypes

- cms/settings/base.py
Since setting the password is what enables basic auth, there is no case where we can end up with needing a default (or if we do we should error out).
> Remove hardcoded password from HTTP basic auth

- cms/core/tests.py
- importer/import_atlas_case_studies.py
- importer/import_blogs.py
- importer/import_pages.py
- importer/import_posts.py
- importer/import_publications.py
- importer/preserve.py
We try to preserve the first_published_date, last_published_date and
latest_revision_created_at from scrapy/WP (where they're called "date"
and "modified") but we weren't correctly preserving them. There's now
a new function in importer/preserve called preserve(obj) that takes
an object and saves it without mangling these features. For the first
write you should manually add the scrapy data to the object before
calling preserve(obj).
> Preserve dates with new function and demo code

- poetry.lock
- pyproject.toml
This fixes an oversight where we updated Wagtail in the dependency lock file, but didn't explicitly pin a higher version in the version specification.
> Explicitly pin latest version of Wagtail in pyproject.toml

- cms/templates/base.html
We were previously using an old filename for these assets.
There remains an open issue to figure out exactly how the asset piping is working here, and see if we can remove the double-loading.
> Use correct CSS and JS from wagtail-nhs-frontend

- README.md
- poetry.lock
- pyproject.toml
This updates the minimum Python version to 2.7, which allows Pillow to update to 9.0.1.
> Update Pillow to 9.0.1

- .coveragerc
Improve the reported test coverage, so we get a more accurate picture of the code we're actually responsible for.
> Refine test coverage

- README.md
- importer/management/commands/parse_stream_fields.py
LGTM analysis has highlighted two instances of code which is fundamentally wrong, either lines which are doing nothing or lines which can lead to entirely unexpected behaviour.
This PR addresses both of those errors, so we only have warnings and recommendations remaining.
> Address errors raised by LGTM

- poetry.lock
- pyproject.toml
This brings the Azure storage interface in django-storages to the latest version to see if it addresses a glitch in staging.
> Bump django-storages[azure] to latest version

- cms/core/models.py
This snuck in during a merge or rebase, and since it only throws a warning we missed it during testing.
> Remove duplicated definition of ExtendedMainMenuItem

- importer/types/import_atlas_case_studies.py
- importer/types/importer_cls.py
- importer/utils.py
This PR corrects the creation of Atlas base page so that `page_mover` import steps can complete successfully.
This also adds extra robustness to category creation to better handle a race condition where the same category can be tried for creation twice before it has reached the category map cache.
> Fixes for page moving and category creation in import process

- importer/types/import_categories.py
The exception thrown with an unmapped category is thrown at the level of the category mapper, where the name of the category is unavailable. This catches the exception a level higher, where the name _is_available, so we can return a more useful error.
> Catch error with unmapped category and return more useful error

- cms/publications/models.py
This makes the handling of H2s which have an existing ID attribute more explicit, solving an issue where we were trying to replace a H2 element which didn't exist.
> Improve handling of H2s with an existing id attribute

- cms/search/templates/search/search.html
- cms/search/tests.py
- cms/templates/partials/nhs_components/pagination.html
- cms/templates/partials/nhs_components/select_search_results_by_order.html
Fix layout page and make pagination a component 
*NOTE TO DEVS* please use the component pages that I specified in the include for that component, to apply your changes in that file please. rather than putting duplicated syntax into the main template.
> Fix rate of page and make pagination a component

- poetry.lock
At some point our `poetry.lock` has become out of step with `pyproject.toml`. This performs an update of dependencies and regenerates the `poetry.lock` so that everything is up to date.
> Update poetry dependencies

- .env.example
* .env.example includes duplicate environment variables for
ElasticSearch. This removes them.
> Remove duplicate ElasticSearch envars

- cms/templates/partials/nhs_components/search_result.html
- packages/custom-styles/_search-results.scss
All search results now include categories (where they exist), linking to the category overview page.
> Add categories to search results

- cms/search/tests.py
- cms/search/views.py
The word 'None' no longer appears in the search bar if the user visits `/search/`
The search bar is empty if you visit `/search/`
> Make search box empty if no query given, not None

- cms/browse/views.py
- cms/templates/partials/nhs_components/nhs_header.html
- packages/custom-styles/_megamenu.scss
The menu link was previously a styled element relying on Javascript to pop the flyover. This is now a proper native link element taking people to Browse if Javascript is disabled.
If we're in the Browse app already, popping the flyover is counter-intuitive and duplicates page content. Instead, just throw people back to the Browse root.
> Improvements to menu button behaviour

- cms/posts/templates/posts/post.html
- cms/posts/tests.py
I have only tested the happy path for this at this moment. It doesn't test if self.last_published_at == self.first_published_at. This is mostly because I couldn't find a post which didn't have any modifications made to it to visually inspect.
This commit only implements the logic for adding the modified dates.
The language used changes throughout the application - it is displayed as `Lastest version` and `Updated on` (shown in screenshots below).
I made the decision to use `Updated on`, but a decision needs to be made about which one should be used.
This also doesn't add in any styling for this logic either. One for future commits.
> Add modified dates to all content pages

- .pre-commit-config.yaml
This solves an issue where black and click wouldn't play nicely together, leading to failures during pre-commit testing.
> Update the version of black in pre-commit

- .github/workflows/test.yml
- cms/publications/models.py
- cms/publications/templates/publications/publication_pdf.html
- cms/publications/tests.py
- cms/publications/views.py
- cms/settings/base.py
- gulpfile.js
- packages/publication_pdf.scss
- poetry.lock
- pyproject.toml
Any publication can now be rendered to PDF by adding `/pdf` to the end of its URL.
This is intentionally a 'bare bones' pass at PDF rendering, as we will no doubt receive further instruction on exactly how a generated PDF should look, additional content which should be included and so-on.
> Add basic rendering of publications to PDF

- .gitignore
- cms/publications/views.py
- cms/settings/base.py
- gulpfile.js
This makes some changes to how the asset pipeline works, namely that the `static` folder is now a place we can put our own static assets, and the output from `npm run build` will end up in `static_compiled`. Running `collectstatic` will then move these to `static_root` for serving or if running with `DEBUG` then they'll be served directly.
The upshot of this is we can include assets without having to mess about changing the asset compilation process itself.
> Improve asset pipeline

- cms/search/tests.py
I have *no* idea why that was there.
> Removed import of socket.PACKET_BROADCAST

- cms/publications/templates/publications/publication.html
- cms/publications/templates/publications/toc.html
- cms/publications/tests.py
- cms/templates/base.html
- packages/custom-styles/_base.scss
- packages/custom-styles/_related-nav.scss
Created the `Content` column
This is comprised of all the `h2` tag headers from the `body` text.
The `Related content` anchor and placeholder has been set up for when this functionality has been set up. The `Related content` functionality is out of scope for this work.
The `Show all updates` frontend is in place. The backend for this is out of scope for this work.
> html document template contents and main page copy

- cms/publications/templates/publications/publication.html
Make the 'download' link for publications point to the auto-generated PDF.
> Add PDF download link to publication template

- .env.example
- importer/websites.py
We keep a default value of the old value to not break people's local devs.
> Specify location of Scrapy server with an environment variable rather than hard coded.

- cms/posts/templates/posts/post.html
- cms/posts/tests.py
Add Header and Body html for News page template
Add meta content 
Add Latest News related content
The related content feature hasn't been implemented yet. The bare bones
has been added in so this can be plugged in once the implementation
has been done.
> Add News page template html

- cms/publications/templates/publications/publication.html
- cms/search/tests.py
- cms/templates/partials/nhs_components/search_result.html
We add the meta description to the top of publications
and also to search results in place of the first twenty words of the body text.
> 216 Publications have introductory blurb

- cms/search/tests.py
- cms/search/views.py
We remove the page from the query but otherwise repeat it verbatim
rather than trying to send a custom crafted message with the fields
that are permissible, since adding an ever-expanding list is error-prone.
> Rewrite forward/backward link code to permit changes in search URLs

- cms/search/tests.py
- cms/templates/partials/nhs_components/search_date_range.html
We want to preserve all the search information so the user can rapidly iterate
their search. We provide the full date, so it's clearer that searching for just
a year includes that entire year.
> Remember dates after user clicks search

- .github/workflows/deployment.yml
- deployment/README.md
* Deploys to the testing environment on push to main
* Changes the GitHub secrets to use environment specific secrets (eg
`TESTING_*`)
* Use `--reuse-values` with helm, rather than specifying them again (The
service should have already been deployed via terraform)
* Add docs on how to generate the GitHub actions credentials
> Update deployment GitHub action

- package-lock.json
- packages/nhsuk.scss
To meet font licensing requirements, disable the inclusion and use of Frutiger and replace with the default fallback font stack in nhsuk-frontend.
- Before launch, [reinstate Frutiger](https://trello.com/c/mIq0qcj8/349-reinstate-frutiger)
> 326 remove frutiger

- cms/pages/templates/pages/base_page.html
- packages/custom-styles/_base.scss
Left hand navigation is now in place.
The links are all children of the current page, with the exception of the top link which is its parent.
`Related content` will sit at the bottom of the left hand navigation, within the list, once the functionality has been implemented outside of this work.
`Show all updates` is currently empty and will need implementing too, for the same reason above
> Add left hand navigation

- deployment/helm/nhsei-scrapy/templates/deployment.yaml
- deployment/helm/nhsei-scrapy/values.yaml
- deployment/helm/nhsei-website/templates/deployment.yaml
- deployment/helm/nhsei-website/values.yaml
- deployment/kubernetes-cron-jobs.tf
- deployment/kubernetes-service-scrapy.tf
- deployment/kubernetes-service-web.tf
- deployment/locals.tf
- deployment/terraform.tfvars.example
- deployment/variables.tf
* Service environment variables can now just be added to the maps in
tfvars, eg. `web_environment_variables` or `scrapy_environment_variables`
* These will be passed through to both the service and cron job
* There is now no requirement to modify the helm charts to add
environment variables in the future
> Refactor service environment variables

- deployment/helm/nhsei-scrapy/templates/deployment.yaml
- deployment/helm/nhsei-website/templates/deployment.yaml
* Ensures the actual environment variable value is used, rather than `$envValue`
> Fix helm chart environment variable values

- deployment/helm/nhsei-website/values.yaml
* Use the set amount of replicas until we can determine which metrics to
scale on
> Disable web autoscaling

- cms/core/blocks.py
- cms/core/templates/blocks/page_heading_block.html
- cms/core/templates/blocks/promo_links_block.html
- cms/core/templates/blocks/recent_posts_block.html
- cms/pages/tests.py
- packages/custom-styles/_base.scss
- Add new layout block for page headings
This is a heading text and optional image designed for landing pages It is different from a text block with right-floating image since it uses the page layout grid.
- Add promoted links blocks
This takes an arbitrary number of links to promote and splits them into rows of no more than 3.
- Add block for recent content
Updates the formatting for the recent posts block so it can be used in landing pages. This content dynamically updates.
> Implement landing page blocks

- importer/category_map.py
- importer/management/commands/delete_media_files.py
- importer/types/import_media_files.py
- importer/types/import_posts.py
- importer/types/import_publication_types.py
- importer/types/import_publications.py
- importer/types/importer_cls.py
The website importer will fail if the regional sites aren't listed in various SOURCES lists or if they have categories that aren't mapped from WordPress to Wagtail. So we add them.
The regional sites haven't been imported before, so they need new
mappings, and there are additional Greener NHS categories. An attempt
has been made at getting plausible mappings.
News and Blogs have been mapped to the correct sections, and "uncategorised" removed.
The less obvious mappings that have been made are:
```
"categories-greenernhs": {
+        "13": ["greener-nhs", "sustainability"], # greener-nhs
```
https://www.england.nhs.uk/greenernhs/category/a-greener-nhs/
```
+        "12": ["greener-nhs", "sustainability"], # greener-nhs, nested
```
(Doesn't actually contain any documents, so irrelevant) …
> Add categories and sources for Greener NHS and regional sites

- cms/core/templates/blocks/acf/visit_nhsuk_infobar_block.html
- cms/home/templates/home/home_page.html
- packages/custom-styles/_phase-banner.scss
- this will need to be merged into parent branch : 193-acf-backend
- Adding the correct markup for the NHS banner and styling it
- Next steps is for developer to apply it in the CMS
> 193 acf frontend nhs banner

- cms/publications/models.py
- cms/search/tests.py
- cms/search/views.py
We think this is causing a problem with Elastic Search.
This does mean we can't search by publication type but having
somewhat-functional search feels like a bonus right now.
Plus, if this works, it's useful diagnostic information.
I can't reproduce the issue locally, even when using elasticsearch
with an imported copy of the database.
https://github.com/wagtail/wagtail/issues/3728 has the same
error:
prefix = definition_model._meta.app_label.lower() + '_' + definition_model.__name__.lower() + '__'
AttributeError: 'NoneType' object has no attribute '_meta'
and looks like it's got the same conflict between "need index to
make something work" and "search_fields contains non-existent field"
> Remove publication_type_id search index and all associated searches and tests

- cms/publications/templates/publications/publication.html
This removes the duplicated metadata, better handles publications with/without various data, and provides a better page flow.
> Rearrange components in publication footer area

- Dockerfile
libpango on buster is 1.42, on bullseye it's 1.46, we need at least 1.44 or to downgrade to weasyprint 52.5.
https://stackoverflow.com/a/68839522/16633550
Upgrading seemed to be the most forward-thinking approach.
> Upgrade to Debian 11 "Bullseye"

- cms/settings/base.py
The British English setting is just because we probably should.
(Document is about 7 minutes old)
Before:
After:
> Set Timezone to allow for DST and language to British English

- cms/pages/templates/pages/base_page.html
- cms/publications/templates/publications/publication.html
- packages/custom-styles/_base.scss
Change to nhsuk-grid-column-one-quarter to reduce the size of left column
Trello: https://trello.com/c/xop8HG2e/370-fe-styling-for-left-nav-seems-too-large
> 370-fe-styling-for-left-nav-width

- packages/custom-styles/_search-results.scss
Styling got lost https://github.com/dxw/nhs-ei.website/pull/154/commits/90e02a518456a006964f9b6c8c185915ff931031#diff-98dde4aa3f2457effdb49503c5b82d2792a22b8c45f487c7f939da62280526ea
Putting back missing styles
Trello: https://trello.com/c/mf0q6oIp/374-fe-right-aline-topic-on-search-results-cards
> Add back missing search styles and right align topic on search results cards
