dxw/nhs-ei.website

docker-compose.yml
importer/websites.py

Get the docker tools talking to each other.

Docker network

---

.github/workflows/test.yml
Dockerfile
docker-compose.test.yml
script/cibuild

- Tests run automatically in Github for all pull requests and pushes to `main`.

Run tests in Github

---

CHANGELOG.md
Dockerfile
docs/application.md
poetry.lock
pyproject.toml
requirements.dev
requirements.txt

[Poetry](https://python-poetry.org/) is now used to handle dependency management.

Use Poetry to handle dependencies

---

importer/import_blogs.py
importer/import_categories.py
importer/import_media_files.py
importer/import_posts.py
importer/import_publication_types.py
importer/import_regions.py
importer/import_settings.py
importer/importer_cls.py
importer/management/commands/delete_media_files.py

This fixes a typo in the imported categories.

Spelling correction for import

---

importer/import_atlas_case_studies.py
importer/import_blogs.py
importer/import_posts.py
importer/import_publications.py
importer/management/commands/runimport.py

Add categories named after the source of files. Also add a category for Atlas since they are likely to get folded into another type of document soon

Source tags

---

cms/settings/base.py
poetry.lock
pyproject.toml

django_extensions adds some quality of life improvements for development.
This also updates us to Wagtail 2.13

Add django_extensions and update dependencies

---

entrypoint.sh

Always auto-migrate regardless of environment variable.

---

script/dumpdb

Add a script that exports a JSON file (using `dumpdata`) suitable for importing into another system.

Create database export script

---

importer/management/commands/make_documents_list.py

* Untrample the "last revision" date.
Will be running a full scrape from e7879b7.

Import date properly

---

script/bash

Modify script/bash so `script/bash staging` will log into the staging pod.

Enable easy bash access to staging/production

---

cms/categories/templates/categories/category_detail.html
cms/categories/templates/categories/category_list.html
cms/categories/tests.py
cms/categories/urls.py
cms/categories/views.py
cms/urls.py

Provide initial stub pages for viewing all categories, and all content within a category.

Implement 'all content in category' page

---

cms/core/templates/blocks/recent_posts_block.html
cms/pages/tests.py

Resize date text

---

script/test

Be able to add arguments to tests to test only one test

---

cms/atlascasestudies/apps.py
cms/blogs/apps.py
cms/categories/apps.py
cms/core/apps.py
cms/pages/apps.py
cms/posts/apps.py
cms/publications/apps.py
cms/settings/base.py
poetry.lock
pyproject.toml

* Changes to apps path to ensure it buids
* Explict setting of type of ID in base to suppress warning

Update django to 3.2.

---

packages/custom-styles/_civic.scss
packages/nhsuk.scss

Accessibility fixes to improve Civic cookie settings banner: 
- better focus states for buttons and controls
- responsive overrides to fill and scale text on smaller viewports/zoomed-in

Fix hover, focus and layout styles for improved accessibility

---

.github/workflows/coverage.yml
poetry.lock
pyproject.toml

This builds and runs but I still don't see output in the coverage section of code climate.

No ticket/fix coverage

---

package-lock.json
package.json

Should resolve https://github.com/dxw/nhs-ei.website/security/dependabot/18 ; might be other issues

Modifications from `npm audit fix`

---

cms/search/templates/search/search.html
cms/static/css/nhsuk.css
cms/templates/base.html
cms/templates/partials/nhs_components/promoted_search-content.html
cms/templates/partials/nhs_components/search_results_bar.html
cms/templates/partials/nhs_components/select_search_results_by_order.html
packages/custom-styles/_search-results.scss

Adding Gov Notification banner component in
- Apply NHS classes and style this component to match the search result's prominent design
- Design: https://xd.adobe.com/view/ad782f93-e7ef-4728-bf8a-db91221585a4-f82b/
- Trello: https://trello.com/c/Y5xarCvh/205-search-template-promoted-search-result-formatting
This to be hooked to the CMS hand over to devs

205 promoted search results box

---

importer/category_map.py

As requested in
https://dxw.slack.com/archives/C027VJH9S3A/p1649256063372259?thread_ts=1649174158.397819&cid=C027VJH9S3A

Add NHS AAC and Survey to Category Map

---

cms/search/templates/search/search.html
cms/static/css/nhsuk.css
cms/templates/base.html
cms/templates/partials/nhs_components/search_results_bar.html
cms/templates/partials/nhs_components/select_search_results_by_order.html
packages/custom-styles/_search-results.scss

Add and style search bar and sort by component
Match design: https://xd.adobe.com/view/ad782f93-e7ef-4728-bf8a-db91221585a4-f82b/
Trello: https://trello.com/c/HoyHVyYY/203-search-template-add-and-arrange-components-to-top-of-results
For the search bar component to feed in the data and the sort by to work with the data.

203-search-template-add-and-arrange-components-to-top-of-results

---

cms/browse/templates/browse/browse.html
cms/browse/templates/partials/corporate_links.html
cms/browse/tests.py
packages/mega-menu.js

Links to the corporate flat menu appeared in the Mega Menu, but not the Browse app. This adds them to the top tier of Browse.

Add corporate links to browse app top level

---

Dockerfile

* To allow us to access the database to aid with debugging

Install psql on image

---

.github/workflows/deployment.yml

* Needs to be `2.0` rather than `2`

Fix deployment GitHub action aks-set-context version

---

.github/workflows/deployment.yml

* nhsei-testing-web is in the 'web' namespace, which needs to be
specified

Fix `helm upgrade` to include namespace

---

deployment/kubernetes-cron-jobs.tf
deployment/kubernetes-service-scrapy.tf
deployment/locals.tf
deployment/terraform.tfvars.example
deployment/variables.tf

* Allow this to be set via tfvars, rather than hardcoded to 'latest'

Add scrapy image tag variable

---

deployment/kubernetes-service-scrapy.tf
deployment/kubernetes-service-web.tf
deployment/locals.tf
deployment/terraform.tfvars.example
deployment/variables.tf

* Allows setting the replica count for services
* Defaults to 3 replicas, to ensure HA across the nodes

Servie replica counts

---

cms/publications/models.py
cms/search/tests.py
cms/search/views.py
cms/templates/partials/nhs_components/search_content_type.html
fixtures/publication_types.README.txt
fixtures/publication_types.json

* Displays publication types for filtering
* Issues with multiple publication types with the same slug and name.
* Preserves ticked boxes across searches
* Shows number of ticked boxes
* Unticks boxes if 'clear' is clicked
* Filters publications (and only publications) by ORing the publication types
* But displays all if none are selected
Ensure dates are populated through searches.

209 Publication type filters in search

---

deployment/README.md

We walked through the documentation and found a few places it might be made clearer.

Update deployment documentation

---

deployment/variables.tf

We're getting mysterious issues on testing (CSRF errors, doubling
of login screens, inability to login) and want to confirm it's not
a problem with multiple things happening at once.

Set number of replicas to 1

---

packages/custom-styles/_print.scss
packages/nhsuk.scss

Overall the print layout looks fine.
removing header and footer
Urls to be printed in full ideally.
remove phase banner
trello: https://trello.com/c/RWAOCBou/149-ensure-print-css-offers-a-sensible-page-layout
in the staging site now that we have data in that site: if we did have more capacity we should do final round of review of the print, once all of the bugs have been addressed

print styles

---

cms/templates/partials/nhs_components/select_search_results_by_order.html

https://trello.com/c/ToJkRKLs/373-devs-sort-by-on-search-results-change-language-choice-to-oldest-and-newest

Change language on search results to match gov.uk, remove published order option from UI

---

packages/custom-styles/_base.scss

remove border in footer
Trello: https://trello.com/c/quTrDpHY/371-fe-random-horizontal-line-at-the-bottom-of-the-html-page

remove border in footer

---

packages/custom-styles/_base.scss

Removing the large white space

white space at top of page needs reducing
